// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvb_qGnj_3TwVTT4hLChu17yVni2WvHns',
    appId: '1:115893884119:web:3c20ad41d65abf3db88c92',
    messagingSenderId: '115893884119',
    projectId: 'lycs-fid-customer',
    authDomain: 'lycs-fid-customer.firebaseapp.com',
    storageBucket: 'lycs-fid-customer.appspot.com',
    measurementId: 'G-4PTMJLZH2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4tJYzp3opoQVl-dRF_EZHIsFjqJ0uPJw',
    appId: '1:115893884119:android:b63e3eb7a5dfc267b88c92',
    messagingSenderId: '115893884119',
    projectId: 'lycs-fid-customer',
    storageBucket: 'lycs-fid-customer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2vaH4GJrf7Q-ZIOrJTZFSwDiffShW7wM',
    appId: '1:115893884119:ios:4d7eea97d9b6b3c8b88c92',
    messagingSenderId: '115893884119',
    projectId: 'lycs-fid-customer',
    storageBucket: 'lycs-fid-customer.appspot.com',
    iosBundleId: 'com.example.lycsFidCustomers',
  );
}
